"""empty message

Revision ID: 343b085ee0f6
Revises: 
Create Date: 2018-03-05 17:56:08.813036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343b085ee0f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mac'), 'user', ['mac'], unique=True)
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('pin', sa.Integer(), nullable=True),
    sa.Column('ap_mac', sa.String(length=17), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_timestamp'), 'auth', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_timestamp'), table_name='auth')
    op.drop_table('auth')
    op.drop_index(op.f('ix_user_mac'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
